[theme]
base = "light"
primaryColor = "#0F6CBD"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#EAF0F6"
textColor = "#172B4D"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
